Blog/APP/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import url

from APP import views

from django.views.decorators.cache import cache_page


urlpatterns = [

    # url(r"index/",cache_page(60*15)(views.IndexView.as_view()),name='index'),
    url(r"index/",views.IndexView.as_view(),name='index'),
    url(r'post/(?P<pk>[0-9]+)/$',views.PostDetailView.as_view(),name='detail'),
    url(r'category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    url(r'tags/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
    url(r'search/',views.search,name='search'),


]

Blog/Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from APP.feed import AllPostRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'app/',include('APP.urls',namespace='blog')),
    url(r'',include('comments.urls',namespace='comment')),
    url(r'rss/',AllPostRssFeed(),name='rss')
]

Blog/comments/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import url

from comments import views

# app_name = 'comments'
urlpatterns = [
    url(r'comment/post/(?P<post_pk>[0-9]+)/',views.post_comment,name='post_comment')
]

Blog/APP/models.py
# -*-coding:utf-8-*-

from django.contrib.auth.models import User
from django.db import models

#分类
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


#标签云
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


#文章
class Post(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    #摘要
    excerpt = models.CharField(max_length=200,blank=True)
    category = models.ForeignKey(Category)
    Tags = models.ManyToManyField(Tag,blank=True)
    #User 是Django 为我们写好的用户模型
    author = models.ForeignKey(User)
    #阅读量
    views = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

Blog/comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible

# Create your models here.
#装饰器用于兼容python2
@python_2_unicode_compatible
class Comment(models.Model):   #评论专区
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=25)
    url = models.URLField(blank=True)
    text = models.TextField()
    #auto_now_add 评论保存到数据库是 自动把created_time指定为当前时间
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('APP.Post')

    def __str__(self):
        return self.text[:20]

Blog/comments/forms.py
# -*-coding:utf-8-*-

from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','url','text']

Blog/APP/views.py
# -*-coding:utf-8-*-
from django.db.models import Q
from django.http import HttpRequest
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension

from APP.models import Post, Category, Tag
import markdown
from comments.forms import CommentForm


class IndexView(ListView,HttpRequest):
    model = Post
    template_name = 'APP/index.html'
    context_object_name = 'post_list'
    paginate_by = 3


#分类
class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(category = cate)

#归档
class ArchivesView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super().get_queryset().filter(created_time__year=year,created_time__month=month)

#标签云
class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(Tags=tag)

#详情页
class PostDetailView(DetailView):
    model = Post
    template_name = 'APP/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 重写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super().get(request,*args,**kwargs)
        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        # 重写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super().get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.tables',
            'markdown.extensions.nl2br',
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        # 重写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板
        context = super(PostDetailView,self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({ 'form': form, 'comment_list': comment_list})
        return context

#简单的全文搜索
def search(request):
    sousuo = request.GET.get('sousuo')
    error_msg = ''
    if not sousuo:
        error_msg = '请输入关键词'
        return render(request,'APP/index.html',{'error_msg':error_msg})
    post_list = Post.objects.filter(Q(title__icontains=sousuo)|Q(body__icontains=sousuo))
    return render(request,'APP/index.html',{'error_msg':error_msg,'post_list':post_list})

Blog/comments/views.py
from django.shortcuts import render,get_object_or_404,redirect

from APP.models import Post

from .forms import CommentForm
from .models import Comment
# Create your views here.


def post_comment(request,post_pk):
    post = get_object_or_404(Post,pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit= False)
            comment.post = post
            comment.save()
            return redirect(post)
        else:
            comment_list = post.comment_set.all()
            context = {'post':post,'form':form,'comment_list':comment_list}
            return render(request,'APP/detail.html',context)

    return redirect(post)

Blog/templates/APP/about.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		 <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
         <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
         <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
         <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

	    <!-- js -->
	    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{% static 'blog/js/script.js' %}"></script>
		
	</body>
</html>

Blog/templates/APP/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>王小强的个人博客</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Html日历插件，Html精美日历插件，Jquery多功能日历插件" />
    <meta name="description" content="Html日历插件" />

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/rili.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container" style="height: 80px">
    <header id="site-header" style="height: 45px">
        <div class="row" style="margin-top: 20px">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h3 style="line-height: 40px"><a href="#">个人博客</a></h3>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" name="sousuo" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
{#<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>#}
{#<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>#}

<div class="content-body">

    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}

                {% endblock %}
            </main>
            <aside class="col-md-4">

               {#日历#}
                <div id="Demo">
                    <div id="CalendarMain">
                        <div id="title"><a class="selectBtn month" href="javascript:"
                                           onclick="CalendarHandler.CalculateLastMonthDays();"><</a><a
                                class="selectBtn selectYear"
                                href="javascript:"
                                onClick="CalendarHandler.CreateSelectYear(CalendarHandler.showYearStart);">2017年</a><a
                                class="selectBtn selectMonth" onClick="CalendarHandler.CreateSelectMonth()">12月</a> <a

                                class="selectBtn nextMonth" href="javascript:"
                                onClick="CalendarHandler.CalculateNextMonthDays();">></a><a
                                class="selectBtn currentDay" href="javascript:"
                                onClick="CalendarHandler.CreateCurrentCalendar(0,0,0);">今天</a>
                        </div>
                        <div id="context">
                            <div class="week">
                                <h3> 一 </h3>
                                <h3> 二 </h3>
                                <h3> 三 </h3>
                                <h3> 四 </h3>
                                <h3> 五 </h3>
                                <h3> 六 </h3>
                                <h3> 日 </h3>
                            </div>
                            <div id="center">
                                <div id="centerMain">
                                    <div id="selectYearDiv"></div>
                                    <div id="centerCalendarMain">
                                        <div id="Container"></div>
                                    </div>
                                    <div id="selectMonthDiv"></div>
                                </div>
                            </div>
                            <div id="foots"><a id="footNow">19:14:34</a></div>
                        </div>
                    </div>
                </div>

{#                目录#}
                {% block toc %}

                {% endblock %}
                <div class="widget widget-recent-posts ">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                         {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                       {% empty %}
                             暂无文章
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">
                                {{ date.year }} 年 {{ date.month }} 月 </a>
                        </li>
                        {% empty %}
                        暂无归档
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
                        </li>
                        {% empty %}
                        暂无分类
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list  %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        暂无标签云
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
{#回到顶部#}
<div class="go-top">
        <div class="arrow"></div>
        <div class="stick"></div>
    </div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">王小强的博客
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="#">博客</a></li>
            <li><a href="#">关于</a></li>
            <li><a href="#">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>
<script src="{% static 'blog/js/rili.js' %}"></script>

</body>
</html>

Blog/templates/APP/contact.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
	    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

	    <!-- js -->
	    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
	    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
	    <script src="{% static 'blog/js/pace.min.js' %}"></script>
	    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{% static 'blog/js/script.js' %}"></script>

	</body>
</html>

Blog/templates/APP/detail.html
{% extends 'APP/base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">{{ post.comment_set.count }}条评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }}人阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comment:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
{#                    <input type="text" id="id_name" name="name" required>#}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
{#                    <input type="email" id="id_email" name="email" required>#}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">网址：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
{#                    <input type="text" id="id_url" name="url">#}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
{#                    <textarea name="comment" id="id_comment" required></textarea>#}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="nickname">{{ comment.name }}</span>
                    <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                    <div class="text">
                        {{ comment.text }}
                    </div>
                </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

{% block toc %}
<div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                            {{ post.toc|safe }}
                </div>
{% endblock %}

Blog/templates/APP/index.html
{% extends 'APP/base.html' %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}

    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }}条评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }}人阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">这个人很懒...什么也没留下</div>
    {% endfor %}
    <br><br>
        <nav aria-label="Page navigation pagination-lg" style="text-align: center">
            <ul class="pagination" >
            {% if is_paginated %}
                <li>
                    <a href={% if page_obj.has_previous %} "?page={{ page_obj.previous_page_number }}
                    {% else %}#{% endif %} " aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>

                {% for p in paginator.page_range %}

                <li>
                    <a href="?page={{ p }}">{{ p }}</a>
                </li>
                {% endfor %}
                <li>
                    <a href="?page={{ paginator.num_pages }}">共{{ paginator.num_pages }}页</a>
                </li>

                <li>
                    <a href={% if page_obj.has_next %}"?page={{ page_obj.next_page_number }}
                      {% else %}#{% endif %}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
{% endblock %}